### PR TITLE
feat: add filters (from vue-moment, MIT licenced)

### PR DESCRIPTION
**Pull request by richie3366**
It was frustrating not to have moment filters available in this nuxt community module.
I think it may be the same case for other nuxt developers, so I decided to share it through this PR.

The code comes from `vue-moment`, which is also a MIT licenced project.

The maintainers are welcome to make the needed edits.

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
@richie3366 I agree we should have these filters. but for me it does not seem right to duplicate the `vue-moment` code, when we should either extend it as a plugin or create a separate module for this

**Comment by pi0** [comment]
I agree PLUS that this should be also optional for disabling

**Comment by HapLifeMan** [comment]
Hey @ricardogobbosouza, I don't understand the problem to duplicate the code...
The licence seems OK and there's no multiple ways to do it...

It would be a **real shame** to not propose that 😕

**Comment by ricardogobbosouza** [comment]
Hi @HapLifeMan, there is no license issue, but copying this code from an existing library is not the purpose of the module, and is harder to maintain.

Note: This library does not appear to be being maintained, it has not been updated for a long time.

**Pull request closed without merging**
